apiVersion: apps/v1
kind: Deployment
metadata:
  name: channelfinder-elasticsearch
  labels:
    {{- include "channelfinder-elasticsearch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channelfinder-elasticsearch
  template:
    metadata:
      labels:
        app: channelfinder-elasticsearch
    spec:
      containers:
        - name: channelfinderservice
          image: "{{ .Values.channelfinderservice.image.repository }}:{{ .Values.channelfinderservice.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.channelfinderservice.resources.limits.cpu }}
              memory: {{ .Values.channelfinderservice.resources.limits.memory }}
            requests:
              cpu: {{ .Values.channelfinderservice.resources.requests.cpu }}
              memory: {{ .Values.channelfinderservice.resources.requests.memory }}
          environment:
            - ELASTICSEARCH_NETWORK_HOST: elasticsearch-cf
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
              memory: {{ .Values.elasticsearch.resources.limits.memory }}
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
          envFrom:
            - configMapRef:
              name: channelfinder-config
