# templates/deployment-channelfinder.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: channelfinderservice
spec:
  replicas: {{ .Values.channelfinderservice.replicas }}
  selector:
    matchLabels:
      app: channelfinderservice
  template:
    metadata:
      labels:
        app: channelfinderservice
    spec:
      containers:
        - name: channelfinderservice
          image: "{{ .Values.channelfinderservice.image.repository }}:{{ .Values.channelfinderservice.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.channelfinderservice.resources.limits.cpu }}
              memory: {{ .Values.channelfinderservice.resources.limits.memory }}
            requests:
              cpu: {{ .Values.channelfinderservice.resources.requests.cpu }}
              memory: {{ .Values.channelfinderservice.resources.requests.memory }}
