# templates/deployment-elasticsearch.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
              memory: {{ .Values.elasticsearch.resources.limits.memory }}
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
